### ISSUE TITLE
SITC Upgrade: re-applying httpd patch

### ISSUE THREAD

**Issue by polikw** [NathanRVance/sitc#1]
In version 0.3.12 beta, unecessarilty reapplying httpd patch to userdir.conf (perhaps upon every other patch or downgrading from Pro to Free):

Installing patch...
patching file /etc/httpd/conf.d/userdir.conf
Reversed (or previously applied) patch detected!  Assume -R? [n] 
Apply anyway? [n] 
Skipping patch.
2 out of 2 hunks ignored -- saving rejects to file /etc/httpd/conf.d/userdir.conf.rej

**Comment by NathanRVance** [comment]
Fixed in most recent commits

**Comment by polikw** [comment]
That's awesome.  Thanks!
